apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: user-service
        metrics_path: /metrics
        static_configs:
          - targets:
              - user-service.staging.svc.cluster.local:8000

      - job_name: student-service
        metrics_path: /metrics
        static_configs:
          - targets:
              - student-service.staging.svc.cluster.local:8000

      - job_name: lecturer-service
        metrics_path: /metrics
        static_configs:
          - targets:
              - lecturer-service.staging.svc.cluster.local:8000

      - job_name: course-service
        metrics_path: /metrics
        static_configs:
          - targets:
              - course-service.staging.svc.cluster.local:8000

      - job_name: enrollment-service
        metrics_path: /metrics
        static_configs:
          - targets:
              - enrollment-service.staging.svc.cluster.local:8000

      - job_name: kube-state-metrics
        static_configs:
          - targets:
              - kube-state-metrics.monitoring.svc.cluster.local:8080
